services:
    _defaults:
        autowire: true
        autoconfigure: true
    Misiyuk\Bundle\MathBundle\Math\Calculator\CalculatorInterface:
        alias: Misiyuk\Bundle\MathBundle\Math\Calculator\Calculator
    Misiyuk\Bundle\MathBundle\Math\:
        resource: '../../Math/*'
        public: true
