services:
    calculator:
        public: true
        class: Misiyuk\Bundle\MathBundle\Math\Calculator\Calculator
    Misiyuk\Bundle\MathBundle\Math\Calculator\CalculatorInterface:
        alias: calculator
